add: Integration test + actions implemented

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -17,6 +17,43 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up Haskell environment
+        uses: actions/setup-haskell@v1
+        with:
+          ghc-version: '8.10.3'
+          cabal-version: '3.2'
+          enable-stack: true
+          stack-version: 'latest'
+
+      - name: Install GMP library
+        run: |
+          sudo apt-get update
+          sudo apt-get install libgmp-dev -y
+
+      - name: Build project
+        run: |
+          make
+
+      - name: Check if a file exists
+        run: |
+          if [ -f "./glados" ]; then
+            echo "Binary exists."
+          else
+            echo "Binary does not exist, check."
+            exit 1  # Exit with a non-zero status code to indicate failure
+          fi
+
+      - name: Integration Tests
+        run: |
+          ./scripts/run-it-bash.sh
+
+      - name: Delete binary
+        run: |
+          make fclean
+
       # - name: Check if 'main' branch exists
       #   run: |
       #     git branch
